version: '3'

services:
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    depends_on:
      - model
    ports:
      - published: 5000
        target: 5000

  frontend:
    build:
      context: .
      dockerfile: ./templates/Dockerfile
    depends_on:
      - backend
    ports:
      - published: 80
        target: 80
    command: ["python", "/app/back/web_interface_flask.py"]

  model:
    build:
      context: ./models
      dockerfile: Dockerfile
    ports:
      - "6000:6000"
