version: "3.9"

services:
  back:
    build:
      context: ./back
    ports:
      - "5001:5001"
    volumes:
      - ./back:/app/back
      - ./templates:/app/templates
    depends_on:
      - models

  models:
    build:
      context: ./models
    volumes:
      - ./models:/app/models
