version: "3.8"

services:
  back:
    build: ./back
    image: moubina/anime:latest
    ports:
      - "5001:5001"
    volumes:
      - ./back:/app/back
      - ./templates:/app/templates
      - ./models:/app/models
    depends_on:
      - prometheus
    environment:
      - PROMETHEUS_ENDPOINT=http://prometheus:9090

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./defaults.ini:/usr/share/grafana/conf/defaults.ini
      - ./grafana.ini:/usr/share/grafana/grafana.ini
    ports:
      - "1000:1000"
    
