version: '3'
services:
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    depends_on:
      - model
    ports:
      - published: 8888
        target: 8888

  frontend:
    build:
      context: ./templates
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - published: 80
        target: 80
    volumes:
      - ./templates:/usr/share/nginx/html
      - ./config:/etc/nginx/conf.d:ro

  model:
    build:
      context: ./models
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
